name: Camera
main: me.chillywilly.CameraPlugin
version: '1.0.5'
author: Chilly_Willy
api-version: 1.20
softdepend: [MultiverseCore, MultiWorld]
website: https://github.com/Chilllyy/CameraPlugin

commands:
  camera:
    permission: camera.admin
    description: Main camera command for setting up photo opportunities

permissions:
  camera.camera:
    default: op
    description: Marks the user as capable of taking pictures