name: Camera
main: me.chillywilly.CameraPlugin
version: '1.0.4'
author: Chilly_Willy
api-version: 1.20
softdepend: [MultiverseCore, MultiWorld]

commands:
  camera:
    permission: camera.admin
    description: Main camera command for setting up photo opportunities

permissions:
  camera.camera:
    default: op
    description: Marks the user as capable of taking pictures